### PR TITLE
Add Windows secure storage support

### PR DESCRIPTION
**Pull request by bb-adam**
This pull request adds support for saving session data to secure storage on Windows platforms. 

It uses the `System.Security.Cryptography.ProtectedData` assembly to achieve this, and the class library project that wraps around this assembly is in the `ProtectedDataWrapper` directory in the root of the repository.

The encrypted data is saved to a binary file in the application's persistent data path, under the name `data.bin`. This of course can change to something more in keeping with the SequenceSDK.

### CODE REVIEW

**Review by BellringerQuinn — APPROVED** [review]
Looks good to me. Just made a small modification - moving the dll into a Windows subfolder for consistency with the other platform specific native code

Thanks for the submission!

**Review by BellringerQuinn — COMMENTED** [review]
Taking a closer look into DPAPI

**Review by BellringerQuinn — CHANGES_REQUESTED** [review]
No changes needed for now; just want to take a closer look

**Comment by bb-adam** [comment]
> Just made a small modification - moving the dll into a Windows subfolder for consistency with the other platform specific native code

Hmm, I need to test our build pipeline to see whether that breaks builds on MacOS. Folder-based dll inclusion is a bit weird when there are import settings on the dll metadata that provide greater control.

**Comment by bb-adam** [comment]
Ok, no issues with build on MacOS after moving DLL to Windows folder 👍

**Review by BellringerQuinn — DISMISSED** [review]

**Review by BellringerQuinn — APPROVED** [review]

**Comment by BellringerQuinn** [comment]
Resolved merge conflicts - feel free to merge when ready 😄 

Thanks for the PR!

**Comment by bb-adam** [comment]
> Resolved merge conflicts - feel free to squash and merge when ready 😄
> 
> Thanks for the PR!

I don't have write access, so I can't merge?

**Pull request merged**
